---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # each hook takes about 1s to run. These are expensive-ish checks
      - id: check-added-large-files
      - id: check-yaml
      - id: check-builtin-literals
        exclude: "examples"
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: forbid-new-submodules
